name: Build Tauri macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt

    - name: Install Tauri dependencies
      run: npm install

    - name: Build Tauri App
      run: npm run tauri build

    - name: Upload macOS App
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: src-tauri/target/release/bundle/dmg/*.dmg

